[package]
name = "bitcoinconsensus"
version = "0.16.1"
authors = ["Tamas Blummer <tamas.blummer@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/tamasblummer/rust-bitcoinconsensus/"
repository = "https://github.com/tamasblummer/rust-bitcoinconsensus/"
description = "Bitcoin's libbitcoinconsensus with Rust binding."
keywords = [ "bitcoin", "bitcoinconsensus", "libbitcoinconsensus" ]
readme = "README.md"
exclude = ["/bitcoin/.github/**", "/bitcoin/.tx/**", "/bitcoin/build-aux/**", "/bitcoin/contrib/**", "/bitcoin/depends/**", "/bitcoin/doc/**", "/bitcoin/share/**", "/bitcoin/test/**"]

[lib]
name = "bitcoinconsensus"
path = "src/lib.rs"

[dependencies]
libc="0.2"
secp256k1="0.8"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
rustc-serialize = "0.3"
